pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh "python http_e.py"
            }
        
        }
        stage('Test') { 
            steps {
                sh 'python RestTest.py'
            }
        }
   
    }
    
}