pipeline {
    agent any
    stages {
        stage('Building ...') {
            steps {
                sh "python3 http_e.py"
            }
        
        }
        stage('testing ...') { 
            steps {
                sh 'pytest TestRest.py'
            }
        }
   
    }
    
}